server:
  port: 3000

settings:
  tankMovementDelay: 1
  tankShootDelay: 2
  explosionTimeMilliseconds: 750
  laserTimeMilliseconds: 750
  tankEnergy: 3
  levelWidth: 12
  levelHeight: 12
  resetSecret: "do not cheat!"